name: Somnia Faucet Daily Bot

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/somniafaucet.yml

jobs:
  start-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Fetch GitHub User Info
        run: |
          GIT_NAME=$(curl -H "Authorization: token ${{ secrets.PRIVATE_SECRET }}" \
                         -H "Accept: application/vnd.github.v3+json" \
                         https://api.github.com/user | jq -r '.login')

          GIT_EMAIL=$(curl -H "Authorization: token ${{ secrets.PRIVATE_SECRET }}" \
                          -H "Accept: application/vnd.github.v3+json" \
                          https://api.github.com/user | jq -r '.email')

          if [ -z "$GIT_EMAIL" ] || [ "$GIT_EMAIL" == "null" ]; then
            GIT_EMAIL="${GIT_NAME}@users.noreply.github.com"
          fi

          echo "GIT_NAME=$GIT_NAME" >> $GITHUB_ENV
          echo "GIT_EMAIL=$GIT_EMAIL" >> $GITHUB_ENV
          
      - name: Install 7zip
        run: sudo apt-get install -y p7zip-full
        
      - name: Write ADDRESS_SECRET to address.txt
        run: |
         echo '${{ secrets.ADDRESS_SECRET }}' > address.txt
        
      - name: Download and Unzip Script
        run: |
          echo "📦 Downloading faucet-somnia.7z..."
          wget https://github.com/0xryd/file_encrypted/raw/main/faucet-somnia.7z -O faucet-somnia.7z

          echo "🔐 Unzipping faucet-somnia.7z with password..."
          7z x faucet-somnia.7z -p${{ secrets.ZIP_PASSWORD }} -o./ || echo "7zip failed!"

      - name: Install Dependencies
        run: npm install

      - name: Run Script
        run: |
          node somniafaucet.js || true

      - name: Update Timestamp File
        run: |
          export TZ="Asia/Jakarta"
          current_time=$(date '+%Y-%m-%d %H:%M:%S')
          echo "Updated on $current_time (UTC+7)" > TIMESTAMP.txt

      - name: Setup Git Configuration
        run: |
          git config user.email "$GIT_EMAIL"
          git config user.name "$GIT_NAME"

      - name: Commit Timestamp Update
        run: |
          git checkout main || git checkout -b main
          git add TIMESTAMP.txt
          git commit -m "Update at $(date '+%Y-%m-%d %H:%M:%S') (UTC+7)" || echo "No changes to commit."

      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

      - name: Cleanup
        run: rm -f address.txt faucet-somnia.7z
